// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChlEHQY20qXPCWkGt7DJn6sHR1MmjRyjc',
    appId: '1:83082004615:web:f16f7e938e41f9d1f29022',
    messagingSenderId: '83082004615',
    projectId: 'gatherup-c7472',
    authDomain: 'gatherup-c7472.firebaseapp.com',
    storageBucket: 'gatherup-c7472.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1WniY7n_Z25ZiTKdo4zoYIb-RZy8-mXs',
    appId: '1:83082004615:android:8b5342cbd8df310ef29022',
    messagingSenderId: '83082004615',
    projectId: 'gatherup-c7472',
    storageBucket: 'gatherup-c7472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYtH2nvXq-fJGFTM25a1TjsghcdyQX-c',
    appId: '1:83082004615:ios:bd1f83267e9c3717f29022',
    messagingSenderId: '83082004615',
    projectId: 'gatherup-c7472',
    storageBucket: 'gatherup-c7472.firebasestorage.app',
    iosBundleId: 'com.example.gatherup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYtH2nvXq-fJGFTM25a1TjsghcdyQX-c',
    appId: '1:83082004615:ios:bd1f83267e9c3717f29022',
    messagingSenderId: '83082004615',
    projectId: 'gatherup-c7472',
    storageBucket: 'gatherup-c7472.firebasestorage.app',
    iosBundleId: 'com.example.gatherup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChlEHQY20qXPCWkGt7DJn6sHR1MmjRyjc',
    appId: '1:83082004615:web:22f0ba9ce7b4bb80f29022',
    messagingSenderId: '83082004615',
    projectId: 'gatherup-c7472',
    authDomain: 'gatherup-c7472.firebaseapp.com',
    storageBucket: 'gatherup-c7472.firebasestorage.app',
  );
}
